### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by kirkins** [mrchimp/surly2#1]
I cloned and ran 

`npm install`

From npm-debug.log:

> 531 verbose pkgid libxmljs@0.17.1
> 532 verbose cwd /home/red/code/surly2
> 533 error Linux 4.4.0-22-generic
> 534 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
> 535 error node v6.2.0
> 536 error npm  v3.8.9
> 537 error code ELIFECYCLE
> 538 error libxmljs@0.17.1 install: `node-gyp rebuild`
> 538 error Exit status 1
> 539 error Failed at the libxmljs@0.17.1 install script 'node-gyp rebuild'.
> 539 error Make sure you have the latest version of node.js and npm installed.
> 539 error If you do, this is most likely a problem with the libxmljs package,
> 539 error not with npm itself.
> 539 error Tell the author that this fails on your system:
> 539 error     node-gyp rebuild
> 539 error You can get information on how to open an issue for this project with:
> 539 error     npm bugs libxmljs
> 539 error Or if that isn't available, you can get their info via:
> 539 error     npm owner ls libxmljs
> 539 error There is likely additional logging output above.
> 540 verbose exit [ 1, true ]

On Ubuntu 16.04

**Comment by mrchimp** [comment]
Having fun?

**Comment by kirkins** [comment]
It was a problem Ubuntu versions. Yes having fun nice work!

**Comment by mrchimp** [comment]
Glad you got it sorted. Anything worth noting for anyone else that might have the same problem or was it purely on your end?

**Comment by kirkins** [comment]
Probably a likely problem if you don't use node.js or npm often on Ubuntu.

I think it had to do with a system change at some point from using
/usr/bin/node to  /usr/bin/nodejs

If you're having a similar problem either install NVM which worked for me
or you can try this:

http://stackoverflow.com/a/18130296/773263

**Comment by kirkins** [comment]
I spun a new server and ended up running into this problem again. Last time me fixing it was sort of a combination of trying a bunch of things and eventually it worked. 

This time I had the problem again and was able to easily fix it by upgrading libxmljs from 0.17.1 to 0.18.0 as suggested here:

https://github.com/libxmljs/libxmljs/issues/421

**Comment by mrchimp** [comment]
Ah. Libxmljs is a massive pain in the arse. I've had loads of problems with
it. Thanks for the feedback. I'm AFK today but will make that fix soon.
