### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Kishore1793** [mrchimp/surly2#3]
While adding libxmljs package it is showing an error. Please help us to fix it.

Error Info :

gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_mo
dules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_mod
ules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\grac
eful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd F:\Kishore\surly-master\surly-master\node_modules\libxmljs
gyp ERR! node -v v8.1.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN Error: EPERM: operation not permitted, rmdir 'F:\Kishore\surly-master\s
urly-master\node_modules'
npm WARN  { Error: EPERM: operation not permitted, rmdir 'F:\Kishore\surly-maste
r\surly-master\node_modules'
npm WARN   errno: -4048,
npm WARN   code: 'EPERM',
npm WARN   syscall: 'rmdir',
npm WARN   path: 'F:\\Kishore\\surly-master\\surly-master\\node_modules' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libxmljs@0.14.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libxmljs@0.14.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\501988\AppData\Roaming\npm-cache\_logs\2017-07-10T10_57_23
_433Z-debug.log

**Comment by mrchimp** [comment]
Ah [this again](https://github.com/mrchimp/surly2/issues/1). Libxmljs and node-gyp cause me problems every time I install them. From the log it looks like you're using libxmljs v0.14.3. Surly2 requires 0.18 so I'm not sure how you've got that. Latest is 0.18.7 so I would try using that.

**Comment by mrchimp** [comment]
Did you get it working?
